Repository fastjs-team/core, pull requests merged in 2024-04, with the labels that each got.

#99 Fix #98: No type exports in entry file
  src/dom/index.ts
  src/main.ts
Labels: Type: Bug, Core Team, Component: Modules, Priority: Important 🚑

#102 Fix: Unexpected result of adding class when create element
  src/dom/dom.ts
  test/unit/dom/dom.test.ts
Labels: Type: Bug, Core Team, Component: Modules, Priority: Minor 💊

#107 Feat: Add cookie module
  src/cookie/cookie-methods.ts
  src/cookie/cookie-types.ts
  src/cookie/cookie.ts
  src/cookie/def.ts
  src/cookie/index.ts
  src/main.ts
  test/unit/cookie/cookie.test.ts
Labels: Core Team, Component: Modules, Type: New Feature, Priority: Nice To Have 🍰

#112 chore: correct link for TypeScript
  packages/create-app/templates/vanilla-ts/src/main.ts
Labels: Type: Language, Priority: Chore 🧹, Scope: Cli

#117 chore: dom func
  packages/core/src/utils/dom.ts
  pnpm-lock.yaml
Labels: Scope: Modules, Status: Pending, Type: Refactor, Priority: Chore 🧹
